### PR TITLE
punktf 2.0.0

### PR DESCRIPTION
**Pull request by Shemnei**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by michidk** [comment]
Wait how was this created? Is this built into the punktf repo? will this always happen automatically?

**Comment by Shemnei** [comment]
> Wait how was this created? Is this built into the punktf repo? will this always happen automatically?

Yep on each release we do an automatic pr will be created here (see [here](https://github.com/Shemnei/punktf/issues/98))

**Comment by Shemnei** [comment]
If this is not wanted, let me know and i will remove it

**Comment by michidk** [comment]
no its quite nice

**Comment by michidk** [comment]
just wondering whether this action should be in this repo instead, so it can be merged automatically

**Pull request merged**
